parameters:
    bukashk0zzz_liip_imagine_serialization.listener.class: Bukashk0zzz\LiipImagineSerializationBundle\EventListener\JmsSerializeListener

services:
    bukashk0zzz_liip_imagine_serialization.listener:
        class: %bukashk0zzz_liip_imagine_serialization.listener.class%
        arguments:
            - "@router.request_context"
            - "@annotations.cached_reader"
            - "@liip_imagine.cache.manager"
            - "@vich_uploader.storage"
        tags:
            - { name: jms_serializer.event_listener, event: serializer.pre_serialize, method: onPreSerialize }
            - { name: jms_serializer.event_listener, event: serializer.post_serialize, method: onPostSerialize }
