---
engines:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "./vendor/escapestudios/symfony2-coding-standard/Symfony2"
      ignore_warnings: true
ratings:
  paths:
    - "**.php"
exclude_paths:
  - .idea/**/*
  - vendor/**/*
